#!/bin/bash
echo "Running: python more_video_control_v2.py &"
python /home/pi/lab2/more_video_control_v2.py &


sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -vo sdl -input file=/home/pi/lab2/video_fifo /home/pi/lab2/bigbuckbunny320p.mp4
